authors:
  mrjulsen:
    name: MrJulsen
    description: "Mod Developer"
    avatar: "https://avatars.githubusercontent.com/u/82165334"
    url: "https://mrjulsen.net"
  andre601:
    name: Andre_601
    description: "Plugin Dev, Wiki manager."
    avatar: "https://avatars.githubusercontent.com/u/11576465"
    url: "https://andre601.ch"