nav:
  - Home:
    - index.md
    - contribute.md
    - mod_translations.md
    - Categories:
      - categories/index.md
      - Create Railways Navigator:
        - categories/create-railways-navigator*.md
      - DragonLib 3:
        - categories/dragonlib*.md
      - TrafficCraft:
        - categories/trafficcraft*.md
      - Create Pantographs & Wires:
        - categories/create-pantographs-and-wires*.md
  - Blog:
    - blog/index.md
  - Create Railways Navigator:
    - createrailwaysnavigator/*
  - Create Pantographs & Wires:
    - create-pantographs-and-wires/*
  - DragonLib 3:
    - dragonlib/*
  - TrafficCraft:
    - trafficcraft/*
    